<?php
require_once "../../widget/widget.lib.functions.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Kaupulehu Beach, Big Island</title>
<meta name="description" content="Kaupulehu Beach is located near the Four Seasons Resort Hualalai on the Big Island's Kohala Coast. It is a sandy beach, but since it has a lava bench, the swimming conditions are poor." />
<meta name="keywords" content="kaupulehu beach, big island, hawaii, photos, reviews, map, weather, location" />
<meta name="robots" content="index,follow" />
<link rel="canonical" href="https://www.to-hawaii.com/big-island/beaches/kaupulehubeach.php" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="shortcut icon" href="../../theme/images/favicon.ico" />
<link href="../../style/style.css" rel="stylesheet" type="text/css" />

<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-9348498266149552",
    enable_page_level_ads: true
  });
</script>
</head>
<body>
<? include ("../../theme/vrtopad.html") ?>
<div class="mainbg">
<div class="sand">
<div class="wrapper">
<div id="main-left"></div>
<div id="main-right">
<div class="main">
<div class="layout">
  <? include ("../../theme/top-bigisland.html") ?><div itemscope="itemscope" itemtype="http://schema.org/TouristAttraction">
  <div class="contentarea">
    <div id="wrapper" class="content_bottom" >
      <? include ("../../theme/left-bigisland.html") ?>
        <div class="midpanel">
          <div class="inner">
<div class="breadcrumbs" align="left">
   <ol class="breadcrumb2020" itemscope itemtype="http://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem"><a itemprop="item" href="../../../">
 <span itemprop="name">Home</span></a>
 <span itemprop="position" content="1">&raquo; </span>
  </li> <li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem">
 <a itemprop="item" href="../../big-island/">
 <span itemprop="name">Big Island</span></a>
 <span itemprop="position" content="2">&raquo; </span>
  </li> <li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem">
 <a itemprop="item" href="../../big-island/beaches/">
 <span itemprop="name">Beaches</span></a>
 <span itemprop="position" content="3"></span>
 &raquo; Kaupulehu Beach</li>
</ol>

</div><h1 class="title"><span itemprop="name">Ka'upulehu Beach</span></h1>
            <div class="clear"></div>
            <div class="new-custom">
              <div class="midpanel_row">
                <div class="gallery-container">
                  <div class="feature"> <img  itemprop="image"  alt="Ka'upulehu Beach" src="../../../big-island/beaches/images/kaupulehubeach/kaupulehu_beach.jpg" />
                    <div class="caption"></div>
                  </div>
                  <div class="gallery">
                    <ul class="thumb-list">
                      <li class="active"><a  rel="../../../big-island/beaches/images/kaupulehubeach/kaupulehu_beach.jpg"  class="galImg"><img src="../../../big-island/beaches/images/kaupulehubeach/kaupulehu_beach.jpg"  class="thumb" alt="Ka'upulehu Beach"  /></a></li>
                      <li><a  rel="../../../big-island/beaches/images/kaupulehubeach/kaupulehu_beach_aerial.jpg"  class="galImg"><img src="../../../big-island/beaches/images/kaupulehubeach/kaupulehu_beach_aerial.jpg"  class="thumb" alt="Ka'upulehu Beach aerial"  /></a> </li>
                    </ul>
                  </div>
                </div>
                <div style="clear:both"></div>
                <h2 class="small">Ka'upulehu Beach, Big Island</h2>
                <p>Ka'upulehu Beach is located near the Four Seasons Resort Hualalai on the Big Island's Kohala Coast. It is a sandy beach, but since it has a lava bench, the swimming conditions are poor. There is only a small sandy area in front of the Kona Village Resort (which is closed indefinitely after sustaining extensive damage in the tsunami on March 11, 2011, which was generated by an earthquake in Japan). </p>
 <? include ("../../theme/text-desktop-only.html") ?>
                <h2 class="big">Ka'upulehu Beach Overview</h2>
                <ul type="disc" class="mylist">
                  <li>Sandy beach with a lava bench</li>
                  <li>Poor swimming conditions</li>
                </ul><div style="clear:both"></div>
<br />
<h3 class="big">Vacation Rentals near Kaupulehu Beach</h3>
<?php
show_widgets('four seasons hualalai','https://www.to-hawaii.com/big-island/vacationrentals/four-seasons-hualalai.php');
?>
                <div id="glowmenu" class="glowingtabs">
                  <table border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr>
                      <td><ul>
                          <li class="selected" id="menu1"><a href="javascript: void(0)" onclick="product('1')"><span>Weather</span></a></li>
<li id="menu2"><a href="javascript: void(0)" onclick="product('2')"><span>Map</span></a></li>
                          <li id="menu3"><a href="javascript: void(0)" onclick="product('3')"><span>Facilities</span></a></li>
                          <li id="menu4"><a href="javascript: void(0)" onclick="product('4')"><span>Activities</span></a></li>
                        </ul></td>
                    </tr>
                  </table>
                </div>
                <div id="tab_container">
                  <div id="contenttab2" style="display:none;">
                    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDD8fQd5oYYE3-H2HcOjd_qjJ1i1dWsjl4&sensor=false"></script>
                    <script>
function initialize() {
var myLatLng = new google.maps.LatLng(19.830185, -155.989920);
var mapOptions = {
    zoom: 15,
    center: myLatLng,
	mapTypeId: google.maps.MapTypeId.HYBRID
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'),
                                mapOptions);

  var image = '../../../images/beachmarker.png';
  var beachMarker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      icon: image
  });
}

</script>
                    <div id="map-canvas" style="width: 100%; height: 300px;"></div>
                    <br />
                    <strong>Location:</strong>
                    <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span itemprop="streetAddress">Off Highway 19</span>, <span itemprop="addressLocality">Kailua-Kona</span> <span itemprop="addressRegion">HI</span> <span itemprop="postalCode">96740</span> </div>
                    <div style="clear:both; height:15px;"></div>
                    <strong>Directions: </strong>From Kona, take Highway 19 north. Right behind Mile Marker #87, make a left turn. Ask for a "public access pass" at the Four Seasons Resort guard house. Make a right turn at the intersection. Follow the road to the parking lot and the public access trail to the beach.</div>
                  <div id="contenttab1" style="display:block;">
                    <a class="weatherwidget-io" href="https://forecast7.com/en/19d64n156d00/kailua-kona/?unit=us" data-label_1="KAILUA-KONA" data-label_2="WEATHER" data-theme="pure" >KAILUA-KONA WEATHER</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>
                  </div>
                  <div id="contenttab3" style="display:none;">
                    <ul type="disc" class="mylist">
                      <li>No facilities</li>
                      <li>No lifeguards</li>
                    </ul>
                  </div>
                  <div id="contenttab4" style="display:none;">
                    <ul type="disc" class="mylist">
                      <li>Limited swimming</li>
                    </ul>
                  </div>
                  <p>
                    <?php $id="813"; include "../../reviews/main.php"; ?>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="space-inner"></div>
        <? include ("../../theme/right-bigisland.html") ?>
        <div class="white-space"></div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<? include ("../../theme/footers.html") ?>
</body>
</html>