<?php
require_once "../../widget/widget.lib.functions.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Hilo Clock, Big Island</title>
<meta name="description" content="The Hilo clock was hit by the 1960 tsunami and since then stands with its hands frozen in time - 1:04 a.m. Townspeople refurbished it, but decided against restoring it to working order in honor of those who perished in the tidal waves." />
<meta name="keywords" content="hilo clock, big island, hilo tsunami, hawaii, photos, reviews, map, weather, location" />
<meta name="robots" content="index,follow" />
<link rel="canonical" href="https://www.to-hawaii.com/big-island/attractions/hiloclock.php" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="shortcut icon" href="../../theme/images/favicon.ico" />
<link href="../../style/style.css" rel="stylesheet" type="text/css" />

<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-9348498266149552",
    enable_page_level_ads: true
  });
</script>
</head>
<body>
<? include ("../../theme/vrtopad.html") ?>
<div class="mainbg">
<div class="sand">
<div class="wrapper">
<div id="main-left"></div>
<div id="main-right">
<div class="main">
<div class="layout">
  <? include ("../../theme/top-bigisland.html") ?><div itemscope="itemscope" itemtype="http://schema.org/TouristAttraction">
  <div class="contentarea">
    <div id="wrapper" class="content_bottom" >
      <? include ("../../theme/left-bigisland.html") ?>
        <div class="midpanel">
          <div class="inner">
<div class="breadcrumbs" align="left">
   <ol class="breadcrumb2020" itemscope itemtype="http://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem"><a itemprop="item" href="../../../">
 <span itemprop="name">Home</span></a>
 <span itemprop="position" content="1">&raquo; </span>
  </li><li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem">
 <a itemprop="item" href="../../big-island/">
 <span itemprop="name">Big Island</span></a>
 <span itemprop="position" content="2">&raquo; </span>
  </li> <li itemprop="itemListElement" itemscope
 itemtype="http://schema.org/ListItem">
 <a itemprop="item" href="../../big-island/attractions/">
 <span itemprop="name">Attractions</span></a>
 <span itemprop="position" content="3"></span>
 &raquo; Hilo Clock</li>
</ol>

</div><h1 class="title"><span itemprop="name">Hilo Clock</span></h1>
            <div class="clear"></div>
            <div class="new-custom">
              <div class="midpanel_row">
                <div class="gallery-container">
                  <div class="feature"> <img  itemprop="image"  alt="Hilo Clock" src="../../../big-island/attractions/images/hiloclock/hilo_clock.jpg" />
                    <div class="caption"></div>
                  </div>
                  <div class="gallery">
                    <ul class="thumb-list">
                      <li class="active"><a  rel="../../../big-island/attractions/images/hiloclock/hilo_clock.jpg" class="galImg"><img src="../../../big-island/attractions/images/hiloclock/hilo_clock.jpg"  class="thumb" alt="Hilo Clock"   /></a></li>
                      <li><a  rel="../../../big-island/attractions/images/hiloclock/1960_tsunami_memorial.jpg" class="galImg"><img src="../../../big-island/attractions/images/hiloclock/1960_tsunami_memorial.jpg"  class="thumb" alt="1960 tsunami memorial" /></a></li>
                      <li><a  rel="../../../big-island/attractions/images/hiloclock/information_and_pictures.jpg" class="galImg"><img src="../../../big-island/attractions/images/hiloclock/information_and_pictures.jpg"  class="thumb" alt="Information and pictures"   /></a> </li>
                    </ul>
                  </div>
                </div>
                <div style="clear:both"></div>
                <h2 class="small">Hilo Clock, Big Island</h2>
                <p>Hilo was hit by tsunamis twice in the past century. The first time was on April 1, 1946, when a tsunami that was generated by a large earthquake off of Alaska hit the cities of Hilo and Laupahoehoe, killing 159 people and causing a lot of damage to Hilo&rsquo;s bayfront and other east-facing shorelines on the Big Island. On May 23, 1960, another tsunami (this time generated by an earthquake off of Chile), again hit Hilo, this time killing 61 people. </p>
                <p>The clock (which stood in the city at that time) was hit by the 1960 tsunami and since then stands with its hands frozen in time &ndash; 1:04 a.m. Townspeople refurbished it, but decided against restoring it to working order in honor of those who perished in the tidal waves. The clock is located on Kamehameha Avenue in front of the Naniloa Golf Course. </p>
                <? include ("../../theme/text.html") ?>
                <h2 class="big">Hilo Clock Overview</h2>
                <ul type="disc" class="mylist">
                  <li>Clock was hit by the 1960 tsunami that hit Hilo</li>
                  <li>Clock stopped working the moment the tidal wave hit Hilo, at 1:04 a.m.</li>
                  <li>Townspeople refurbished the clock, but didn't restore it to working order in honor of those who died</li>
                  <li>Today, the clock is a memorial</li>
                </ul><div style="clear:both"></div>
<br />
<h3 class="big">Vacation Rentals near Hilo Clock</h3>
<?php
show_widgets('Hilo District','https://www.to-hawaii.com/big-island/vacationrentals/hilo-district.php');
?>

                <div id="glowmenu" class="glowingtabs">
                  <table border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr>
                      <td><ul>
                          <li class="selected" id="menu1"><a href="javascript: void(0)" onclick="product('1')"><span>Weather</span></a></li>
<li id="menu2"><a href="javascript: void(0)" onclick="product('2')"><span>Map</span></a></li>
                        </ul></td>
                    </tr>
                  </table>
                </div>
                <div id="tab_container">
                  <div id="contenttab2" style="display:none;">
                    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDD8fQd5oYYE3-H2HcOjd_qjJ1i1dWsjl4&sensor=false"></script>
                    <script>
function initialize() {
var myLatLng = new google.maps.LatLng(19.722741, -155.067445);
var mapOptions = {
    zoom: 17,
    center: myLatLng,
	mapTypeId: google.maps.MapTypeId.HYBRID
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'),
                                mapOptions);

  var image = '../../../images/beachmarker.png';
  var beachMarker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      icon: image
  });
}

</script>
                    <div id="map-canvas" style="width: 100%; height: 300px;"></div>
                    <br />
                    <strong>Location:</strong>
                    <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span itemprop="streetAddress">Kamehameha Ave</span>, <span itemprop="addressLocality">Hilo</span> <span itemprop="addressRegion">HI</span> <span itemprop="postalCode">96720</span> </div>
                    <div style="clear:both; height:15px;"></div>
                    <strong>Directions: </strong>The clock is located on Kamehameha Avenue in front of the Naniloa Golf Course.</div>
                  <div id="contenttab1" style="display:block;">
                 <a class="weatherwidget-io" href="https://forecast7.com/en/19d71n155d09/hilo/?unit=us" data-label_1="HILO" data-label_2="WEATHER" data-theme="pure" >HILO WEATHER</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>
                  </div>
                  <p>
                    <?php $id="763"; include "../../reviews/main.php"; ?>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="space-inner"></div>
        <? include ("../../theme/right-bigisland.html") ?>
        <div class="white-space"></div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<? include ("../../theme/footers.html") ?>
</body>
</html>