<?php
require_once "../widget/widget.lib.functions.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>&Eacute;ducation &agrave; Hawaii</title>
<meta name="description" content="L'&eacute;ducation &agrave; Hawaii, de la maternelle au doctorat." />
<meta name="keywords" content="&eacute;ducation, Hawaii, &eacute;coles, maternelle, doctorat, Oahu, Maui, Kauai" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="shortcut icon" href="../theme/images/favicon.ico" />
<link href="../style/style.css" rel="stylesheet" type="text/css" />
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-9348498266149552",
    enable_page_level_ads: true
  });
</script>
</head>
<body>
<? include ("../theme/vrtopad.html") ?>
<div class="mainbg">
<div class="sand">
<div class="wrapper">
<div id="main-left"></div>
<div id="main-right">
<div class="main">
  <div class="layout">
    <? include ("../theme/languages/fr-top.html") ?>
    <div class="contentarea">
      <div id="wrapper" class="content_bottom" >
        <? include ("../theme/languages/fr-left.html") ?>
        <div class="midpanel">
          <div class="inner">
           <h1>&Eacute;ducation &agrave; Hawaii</h1>
            <div class="midpanel_row">
              <h2>L'&eacute;ducation &agrave; Hawaii, de la maternelle au doctorat</h2>
              <p>Depuis l'arriv&eacute;e des missionnaires en 1820, l'&eacute;ducation  s'est rapidement d&eacute;velopp&eacute;e &agrave; Hawaii. En 2000, 84.6% de tous les hawaiiens de  25 ans ou plus ont poursuivi leurs &eacute;tudes jusqu'au lyc&eacute;e et 26.2% ont pass&eacute;  quatre ans ou plus au coll&egrave;ge.</p>
              <p>Hawaii est le seul Etat des Etats-Unis ayant un syst&egrave;me  d'&eacute;cole public unique, unifi&eacute; et national, fond&eacute; en 1840. Au lieu que chaque  quartier g&egrave;re ses propres &eacute;coles de fa&ccedil;on ind&eacute;pendante, il n'y a qu'un seul  syst&egrave;me centralis&eacute;, situ&eacute; sur Oahu, et qui d&eacute;cide de l'&eacute;ducation des enfants  pour tout Hawaii et ses 284 &eacute;coles publics. Un avantage est que le financement  et les ressources humaines sont r&eacute;partis de fa&ccedil;on &eacute;gale. Un inconv&eacute;nient est  l'inertie administrative qui &eacute;touffe la flexibilit&eacute; et les initiatives.</p>
              <p>Environ 18% des enfants scolaris&eacute;s hawaiiens fr&eacute;quentent  l'une des 128 &eacute;coles priv&eacute;s, qui b&eacute;n&eacute;ficient d'une bonne r&eacute;putation mais qui,  se finan&ccedil;ant par leurs propres moyens, sont en plus ch&egrave;res. Le pourcentage  d'&eacute;tudiants hawaiiens dans une &eacute;cole priv&eacute; est le plus &eacute;lev&eacute; de tous les  Etats-Unis. Ces &eacute;coles priv&eacute;es diff&egrave;rent dans leurs tailles, leurs programmes  et leurs prix. Certaines se concentrent sur la pr&eacute;paration aux cursus  universitaires, d'autres par exemple sur le d&eacute;veloppement personnel ou  l'&eacute;quilibre avec le temps libre. Voi&ccedil;i une vue d'ensemble de certaines de ces  &eacute;coles priv&eacute;es.</p>
              <h3>Les &eacute;coles priv&eacute;es &agrave; Hawaii</h3>
              <p>Consid&eacute;r&eacute;e comme la meilleure &agrave; Hawaii, la <span class="subtitle">Punahou School</span> est une &eacute;cole mixte priv&eacute;e, ouverte &agrave; tous, situ&eacute;e &agrave; Honolulu sur Oahu. Elle  accueille 3700 &eacute;tudiants de la maternelle au lyc&eacute;e, ce qui en fait l'une des  plus grandes &eacute;coles ind&eacute;pendantes des Etats-Unis.</p>
              <p>La Punahou School a &eacute;t&eacute; cr&eacute;&eacute; en 1841 et &eacute;tait &agrave; l'origine  une &eacute;cole pour les enfants des missionnaires congr&eacute;gationalistes. L'&eacute;cole  portait le nom d'Oahu College de 1859 &agrave; 1934. Elle est list&eacute;e dans le Registre  national des Places historiques. L'&eacute;cole se concentre sur la pr&eacute;paration aux  cursus universitaires. Grace &agrave; sa tradition d'excellence acad&eacute;mique et  sportive, l'&eacute;cole a une renomm&eacute;e nationale.</p>
              <p>Le programme sportif de Punahou est l'un des meilleurs de la  nation. En 2005, &quot;Sports Illustrated&quot; l'a class&eacute; en quatri&egrave;me  position dans le classement des universit&eacute;s am&eacute;ricaines. Les &eacute;quipements sont d'excellente  qualit&eacute; et comprennent une piscine chauff&eacute;e de taille olympique et une piste  d'athl&eacute;tisme &agrave; 8 couloirs. Les &eacute;tudiants peuvent pratiquer 22 sports, comme le  tir aux armes &agrave; air comprim&eacute;, le baseball, le basket, le bowling, le cross, le  football, le golf, la gymnastique, la voile, le soccer, la natation, la  plong&eacute;e, le tennis, la lutte, et bien d'autres encore.</p> <?php
show_widgets('','https://www.to-hawaii.com/vacation-rentals.php','rating_desc');
?>
              <p>En plus de ses cons&eacute;quents programmes sportifs, Punahou  propose d'excellents cursus artistiques. Les programmes de danses, de th&eacute;&acirc;tre  et de musique b&eacute;n&eacute;ficient d'une reconnaissance nationale. Les &eacute;tudiants ont  aussi acc&egrave;s &agrave; une fabrique de bijoux, une chambre noire pour d&eacute;velopper des  photos et d'&eacute;quipement pour fabriquer du verre.</p>
              <p>L'<span class="subtitle">Iolani Schoo</span>l est une &eacute;cole priv&eacute;e mixte offrant une &eacute;ducation  &agrave; plus de 1800 &eacute;tudiants de la maternelle &agrave; lyc&eacute;e. Elle a &eacute;t&eacute; fond&eacute;e en 1863  par le P&egrave;re William R. Scott et par la suite a &eacute;t&eacute; fr&eacute;quent&eacute;e par le Roi  Kamehameha IV et la Reine Emma, qui donna son nom actuel &agrave; l'&eacute;cole en 1870.  Aujourd'hui, Iolani Scholl est affili&eacute;e &agrave; l'&Eacute;glise &Eacute;piscopale des Etats-Unis.  Elle est administr&eacute;e par un conseil sup&eacute;rieur et est l'une des plus grandes  &eacute;coles ind&eacute;pendantes de la nation.</p>
              <p>L'Iolani School est situ&eacute;e &agrave; Honolulu sur Oahu. Sa  principale mission est de la pr&eacute;paration aux &eacute;coles sup&eacute;rieures et une solide  formation sportive. Plus de 70% de tous ses &eacute;tudiants font partie d'une &eacute;quipe  de sport dans l'un des 32 sports de comp&eacute;tition propos&eacute;s par l'&eacute;cole.</p>
              <p>Les <span class="subtitle">Kamehameha Schools</span> sont des &eacute;coles priv&eacute;es mixtes  proposant leurs services &agrave; plus de 6500 jeunes de la maternelle au lyc&eacute;e. Le  r&eacute;seau d'&eacute;coles a &eacute;t&eacute; fond&eacute; en 1887 via le testament de Bernice Pauahi Bishop,  un membre de la famille royale de Kamehameha I. Ces &eacute;coles acceptent en  priorit&eacute; les hawaiiens d'origine. Entrer dans une Kamehameha School est  consid&eacute;r&eacute; comme un privil&egrave;ge, et cette politique de n'accepter que les  hawaiiens de souche fait d&eacute;bat chez certains qui aimeraient imposer leurs  crit&egrave;res plut&ocirc;t que laisser l'&eacute;cole souveraine dans ses choix. Depuis 1965, les  Kamehameha Schools ont en effet exclut tous les &eacute;trangers sauf deux.</p>
                            <p>L'&eacute;cole a un campus sur Oahu, un sur Maui et un sur l'&Icirc;le  Principale. Le campus principal se trouve &agrave; Honolulu (Oahu), dans les hauteurs  de Kapalama. Les frais d'inscription sont bien moindres que ceux des autres  &eacute;coles priv&eacute;es. L'&eacute;cole est financ&eacute;e par l'&eacute;v&ecirc;ch&eacute;. Son orientation religieuse  est protestante. Elle propose principalement une pr&eacute;paration aux &eacute;coles  sup&eacute;rieures et une formation artistique d&eacute;velopp&eacute;e.</p>
              <p>La <span class="subtitle">Maryknoll School</span> est une &eacute;cole priv&eacute;e mixte, de  confession catholique, au service de 1400 jeunes de la cr&egrave;che au lyc&eacute;e. Situ&eacute;e  &agrave; Honolulu sur Oahu, l'&eacute;cole est administr&eacute;e par le Dioc&egrave;se d'Honolulu en  association avec les fondateurs de l'&eacute;cole, la soci&eacute;t&eacute; de pr&egrave;tres et moines de  Maryknoll et la Congr&eacute;gation de maryknoll (les Soeurs de Maryknoll). La  Maryknoll School est ouverte &agrave; tous les enfants hawaiiens, quelque soit leur  origine ou conviction religieuse.</p>
              <p>La <span class="subtitle">Sacred Hearts Academy</span> est une &eacute;cole catholique priv&eacute;e  pour filles. Fond&eacute;e en 1909, elle se trouve &agrave; Honolulu sur Oahu et ouvre ses  portes aux enfants de la maternelle au lyc&eacute;e. Elle est affili&eacute;e avec les P&egrave;res  Picpus de la Congr&eacute;gation des Sacr&eacute;s Coeurs de J&eacute;sus et Marie.</p>
              <p>Cette institution offre une pr&eacute;paration aux grandes &eacute;coles  aux filles de diverses origines religieuses, sociales, &eacute;conomiques et de  diverses capacit&eacute;s. Elle est centr&eacute;e sur la personne et sur des valeurs, la  coop&eacute;ration, le respect mutuel, la r&eacute;solution pacifique des conflits et le sens  du service.</p>
              <p>La <span class="subtitle">Damien Memorial School</span> est une &eacute;cole priv&eacute;e catholique  pour gar&ccedil;ons &agrave; Honolulu. Elle a ouvert ses portes en 1959 et est sponsoris&eacute;e  par la Congr&eacute;gation des Fr&egrave;res Chr&eacute;tiens. Elle est ouverte aux gar&ccedil;ons du  coll&egrave;ge au lyc&eacute;e.</p>
              <p>L'environnement scolaire dans cette &eacute;cole est strict,  traditionnel et orient&eacute; vers l'autonomie des &eacute;l&egrave;ves. Chaque &eacute;tudiant est plac&eacute;  dans un cursus adapt&eacute; &agrave; ses propres capacit&eacute;s. Il y a des titres honorifiques  pour les plus dou&eacute;s, ainsi que des programmes sp&eacute;ciaux permettant &agrave; ceux qui le  souhaitent de gagner des cr&eacute;dits universitaires tout en &eacute;tant encore dans le  secondaire.</p>
              <p>L'<span class="subtitle">Honolulu Waldorf School</span> est un autre &eacute;cole priv&eacute;e mixte,  de 300 &eacute;l&egrave;ves de la primaire au lyc&eacute;e. Fond&eacute;e en 1961, elle est situ&eacute;e sur deux  campus, l'un couvrant les sections primaires et coll&egrave;ges, dans Niu Valley &agrave;  Honolulu Est, et l'autre accueillant les &eacute;l&egrave;ves du niveau troisi&egrave;me &agrave; terminal,  &agrave; Kahala, dans la banlieue d'Honolulu.</p>
              <p>L'Honolulu Waldorf School est l'une des 1000 &eacute;coles Waldorf  dans le monde. Sa philosophie est une approche de l'&eacute;ducation centr&eacute;e sur le  d&eacute;veloppement de l'enfant et les diff&eacute;rents stades de sa croissance. La  cr&eacute;ativit&eacute; et l'esprit critique sont encourag&eacute;s et le programme &eacute;ducatif de  l'&eacute;cole comprend une partie artistique, une partie exp&eacute;rimentale, pratique, et  une partie scolaire. L'&eacute;tude d'une langue &eacute;trang&egrave;re est obligatoire d&egrave;s le  niveau CP, et les arts, la musique, le th&eacute;&acirc;tre font partie du quotidien des  &eacute;l&egrave;ves &agrave; Waldorf.</p>
              <p>La <span class="subtitle">Montessori Community School</span> est une &eacute;cole priv&eacute;e,  ind&eacute;pendante et mixte fournissant une &eacute;ducation aux enfants de deux &agrave; douze  ans. Fond&eacute;e en 1972, la Montessori Community School &agrave; Honolulu est l'une des  plus de 4000 &eacute;coles Montessori du pays. L'&eacute;cole est une organisation &agrave; but non  lucratif et est dirig&eacute;e par un conseil sup&eacute;rieur.</p>
              <p>L'&eacute;ducation Montessori est bas&eacute;e sur les principes  d&eacute;velopp&eacute;s par le Docteur Maria Montessori, n&eacute; en Italie en 1870. Elle devint  la premi&egrave;re femme a obtenir un dipl&ocirc;me de physique en Italie. Toute sa vie,  elle a travaill&eacute; avec des enfants et a d&eacute;velopp&eacute; un savoir-faire &eacute;ducatif  unique et innovant, qui respecte le d&eacute;veloppement naturel de l'enfant. Dans une  &eacute;cole Montessori, l'enseignant est moins un professeur qu'un guide. Les enfants  sont encourag&eacute;s &agrave; &quot;apprendre &agrave; apprendre&quot;. En d'autres mots, la  philosophie de l'&eacute;ducation Montessori est une &eacute;ducation qui se vit.</p>
              <p>Fond&eacute;e en 1949, la <span class="subtitle">Hawaii Preparatory Academy</span> est une &eacute;cole  priv&eacute;e, ind&eacute;pendante, mixte, enseignant de la maternelle au lyc&eacute;e. Elle a aussi  un pensionnat pour les enfants de dix &agrave; dix-huit ans. Ses 600 &eacute;tudiants  viennent du monde entier.</p>
              <p>La Hawaii Preparatory Academy est &agrave; Waimea (Kamuela) sur  l'&Icirc;le Principale d'Hawaii. Elle a deux campus, la Lower and Middle School  (&eacute;cole primaire et coll&egrave;ge) est situ&eacute; sur trois hectares au beau milieu de la  campagne hawaiienne, tandis que la Upper School (lyc&eacute;e) se trouve &agrave; deux  kilom&egrave;tre au pied des montagnes de Kohala.</p>
              <p>De la seconde &agrave; la terminale, l'accent est mis sur la  pr&eacute;paration aux grandes &eacute;coles et les connaissances essentielles dans nombres  de domaines. Le ratio d'&eacute;l&egrave;ves allant en facult&eacute; sur le total est de 1 sur 10.  Les &eacute;l&egrave;ves peuvent rencontrer les professeurs sept jours par semaine, faire du  tennis en int&eacute;rieure, ont acc&egrave;s &agrave; des centres de loisirs, un piscine, des  ordinateurs,...</p>
              <p>L'<span class="subtitle">Island School</span> est une &eacute;cole priv&eacute;e et mixte situ&eacute; &agrave; Lihue  sur Kauai. Elle pr&eacute;pare les &eacute;tudiants aux &eacute;coles sup&eacute;rieures, de la maternelle  au lyc&eacute;e.</p>
              <p>Sa philosophie est bas&eacute;e sur le concept du mouvement  progressif pour lequel l'&eacute;ducation doit aider l'enfant &agrave; d&eacute;velopper un int&eacute;r&ecirc;t  pour le monde qui l'entoure, &agrave; avoir un esprit critique et devenir un membre  actif de la communaut&eacute;. Les services &agrave; la communaut&eacute; font partie du programme  est les &eacute;tudiants participent &agrave; divers activit&eacute;s de charit&eacute;s.</p>
              <p>Tous les &eacute;tudiants sont aussi encourag&eacute;s &agrave; d&eacute;velopper un  talent artistique, que ce soit dans la danse, le th&eacute;&acirc;tre ou la peinture. Ils  peuvent aussi participer &agrave; divers clubs de sports.</p>
              <p>La <span class="subtitle">Seabury Hall</span> est une &eacute;cole pr&eacute;paratoire mixte et priv&eacute;e,  qui se trouve sur un campus de 22 hectares, &agrave; trois kilom&egrave;tre au nord de  Makawao Town sur Maui. L'&eacute;cole a &eacute;t&eacute; fond&eacute;e en 1964 et est affili&eacute; &agrave; l'Eglise  Episcopale. Seabury Hall accueille 400 &eacute;tudiants de coll&egrave;ge au lyc&eacute;e. Elle est  financ&eacute;e principalement par les frais de scolarit&eacute; et gouvern&eacute;e par un conseil  d'administration.</p>
              <p>La Seabury Hall s'est vu remettre le Blue Ribbon, une  distinction du minist&egrave;re am&eacute;ricain de l'&eacute;ducation pour les performances en  mati&egrave;re d'&eacute;ducation qui est donn&eacute;e &agrave; moins d'un pourcent des &eacute;coles  am&eacute;ricaines. En 1999, l'&eacute;cole a aussi &eacute;t&eacute; admise &agrave; la Cum Laude Society, une  soci&eacute;t&eacute; des &eacute;coles secondaires nationales.</p>
                     </div>
        </div>
      </div>
      <div class="space-inner"></div>
      <? include ("../theme/languages/fr-right.html") ?>
      <div class="white-space"></div>
      <div class="clear"></div>
    </div>
  </div>
</div>
<? include ("../theme/languages/fr-footer.html") ?>
</body>
</html>